"""Phase-0 re-ingest pipeline.

Pulls chunks from a source Pinecone index, reconstructs documents when
metadata supports it, semantic re-chunks with Cohere, enriches metadata
via LLM, and upserts into a target index/namespace.

Idempotent: ``ingest_jobs.processed_chunks`` advances per upsert; rerunning
resumes from offset (NFR-REL-6).

Usage:
    python -m app.scripts.reingest <ingest_job_id>
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import uuid
from datetime import datetime
from pathlib import Path
from string import Template
from typing import Any

from sqlalchemy.orm import Session

from app.db.database import SessionLocal
from app.models.index_registry import IndexRegistry
from app.models.ingest_job import IngestJob
from app.services.chunking_service import semantic_chunk_text
from app.services.embedding_service import generate_embeddings_cohere_batch
from app.services.llm_service import call_openai_json
from app.services.pinecone_service import get_factory

_log = logging.getLogger(__name__)

_BATCH_SIZE = 96  # Cohere embed batch limit
_FAILURE_THRESHOLD = 0.05  # halt at 5% chunk failure rate
_METADATA_MODEL = "gpt-4.1-mini"
_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "metadata_enrich.txt"


async def fetch_source_chunks(
    index_name: str, project_id: str, batch_size: int = 100,
) -> list[dict[str, Any]]:
    """Paginate the source index, return all chunks with metadata.

    Uses ``list_paginated`` to iterate vector IDs, then ``fetch`` in batches
    to pull text + metadata. Vector values are NOT returned — they'll be
    re-generated by Cohere v3 in the ingest pipeline.
    """
    factory = get_factory()
    client = factory.get_client(project_id)
    index = client.Index(index_name)

    all_ids: list[str] = []
    cursor: str | None = None
    while True:
        page = index.list_paginated(limit=batch_size, pagination_token=cursor)
        all_ids.extend(v.id for v in page.vectors)
        cursor = page.pagination.next if page.pagination else None
        if not cursor:
            break

    chunks: list[dict[str, Any]] = []
    for i in range(0, len(all_ids), 100):
        batch = all_ids[i:i + 100]
        fetched = index.fetch(ids=batch)
        for vid, vec in fetched.vectors.items():
            md = vec.metadata or {}
            chunks.append({"id": vid, "text": md.get("text", ""), "metadata": md})
    return chunks


def reconstruct_documents(chunks: list[dict[str, Any]]) -> dict[str, str]:
    """Group chunks back into source documents by ``source_id`` where
    available. Chunks without ``source_id`` are kept as standalone documents
    keyed by ``_orphan_<i>``."""
    grouped: dict[str, list[tuple[int, str]]] = {}
    orphans: list[str] = []
    for c in chunks:
        md = c.get("metadata") or {}
        sid = md.get("source_id")
        if sid:
            pos = md.get("chunk_position", 0)
            grouped.setdefault(sid, []).append((pos, c["text"]))
        else:
            orphans.append(c["text"])

    docs: dict[str, str] = {}
    for sid, items in grouped.items():
        items.sort(key=lambda t: t[0])
        docs[sid] = "\n\n".join(text for _, text in items)
    for i, text in enumerate(orphans):
        docs[f"_orphan_{i}"] = text
    return docs


async def enrich_metadata(chunk_text: str) -> dict[str, Any]:
    """LLM pass to extract topic_tags, source_type, public_safe."""
    prompt = Template(_PROMPT_PATH.read_text()).safe_substitute(
        chunk_text=chunk_text[:2000]
    )
    return await call_openai_json(
        model=_METADATA_MODEL, system="", user=prompt, temperature=0
    )


async def run_ingest_job(job_id: str) -> None:
    """Execute or resume an ingest job. Idempotent at the chunk-batch level.

    Pipeline per job:
      1. fetch source chunks
      2. reconstruct documents by source_id
      3. semantic re-chunk each document
      4. for each Cohere-batch of new chunks: enrich metadata, embed, upsert
      5. advance processed_chunks per batch
      6. halt with status='failed' if failure rate > 5%
    """
    db: Session = SessionLocal()
    try:
        job = db.query(IngestJob).filter(
            IngestJob.id == uuid.UUID(job_id)
        ).first()
        if not job:
            raise ValueError(f"Job {job_id} not found")
        if job.status == "completed":
            _log.info("Job %s already completed", job_id)
            return

        job.status = "running"
        if not job.started_at:
            job.started_at = datetime.utcnow()
        db.commit()

        try:
            project_id = job.config.get("source_project_id", "1")
            source_chunks = await fetch_source_chunks(job.source_index, project_id)
            documents = reconstruct_documents(source_chunks)

            new_chunks: list[dict[str, Any]] = []
            for sid, doc_text in documents.items():
                if not doc_text.strip():
                    continue
                pieces = semantic_chunk_text(doc_text)
                for pos, piece in enumerate(pieces):
                    new_chunks.append({
                        "source_id": sid,
                        "chunk_position": pos,
                        "doc_total_chunks": len(pieces),
                        "text": piece,
                    })

            job.total_chunks = len(new_chunks)
            db.commit()

            factory = get_factory()
            target = factory.get_client(project_id).Index(job.target_index)

            start = job.processed_chunks
            for batch_start in range(start, len(new_chunks), _BATCH_SIZE):
                batch = new_chunks[batch_start:batch_start + _BATCH_SIZE]
                texts = [c["text"] for c in batch]
                embeddings = generate_embeddings_cohere_batch(
                    texts, input_type="search_document"
                )

                vectors = []
                for c, emb in zip(batch, embeddings):
                    try:
                        meta = await enrich_metadata(c["text"])
                    except Exception as exc:
                        _log.warning("metadata enrich failed: %s", exc)
                        meta = {
                            "topic_tags": [],
                            "source_type": "other",
                            "public_safe": False,
                        }
                    vid = (
                        f"{c['source_id']}_{c['chunk_position']}_"
                        f"{uuid.uuid4().hex[:8]}"
                    )
                    domain = job.target_index.replace("max-", "")
                    full_meta = {
                        "text": c["text"][:40000],
                        "source_type": meta.get("source_type", "other"),
                        "source_id": c["source_id"],
                        "ingested_at": datetime.utcnow().isoformat(),
                        "domain": domain,
                        "namespace": job.target_namespace,
                        "topic_tags": meta.get("topic_tags", []),
                        "public_safe": bool(meta.get("public_safe", False)),
                        "embedding_model": "cohere-embed-v3",
                        "chunk_position": c["chunk_position"],
                        "doc_total_chunks": c["doc_total_chunks"],
                    }
                    vectors.append({"id": vid, "values": emb, "metadata": full_meta})

                try:
                    target.upsert(vectors=vectors, namespace=job.target_namespace)
                    job.processed_chunks = batch_start + len(batch)
                except Exception as exc:
                    _log.error("upsert failed at offset %s: %s", batch_start, exc)
                    job.failed_chunks += len(batch)

                db.commit()

                if (
                    job.total_chunks
                    and job.failed_chunks / job.total_chunks > _FAILURE_THRESHOLD
                ):
                    raise RuntimeError(
                        f"Failure rate exceeded {_FAILURE_THRESHOLD * 100:.0f}% threshold"
                    )

            job.status = "completed"
            job.completed_at = datetime.utcnow()
            db.commit()
        except Exception as exc:
            job.status = "failed"
            job.error_message = str(exc)
            db.commit()
            raise
    finally:
        db.close()


async def snapshot_to_legacy(
    source_index: str,
    source_project: str,
    archive_index: str,
) -> int:
    """Copy raw chunks from source to legacy-archive without re-chunking or
    re-embedding (zero-loss safety backup per NFR-DATA-1)."""
    factory = get_factory()
    source = factory.get_client(source_project).Index(source_index)
    archive = factory.get_client(source_project).Index(archive_index)

    cursor: str | None = None
    total = 0
    while True:
        page = source.list_paginated(limit=100, pagination_token=cursor)
        ids = [v.id for v in page.vectors]
        if ids:
            fetched = source.fetch(ids=ids)
            vectors = [
                {
                    "id": f"{source_index}__{vid}",
                    "values": v.values or [0.0],
                    "metadata": {
                        **(v.metadata or {}),
                        "_source_index": source_index,
                    },
                }
                for vid, v in fetched.vectors.items()
            ]
            if vectors:
                archive.upsert(vectors=vectors, namespace=source_index)
                total += len(vectors)
        cursor = page.pagination.next if page.pagination else None
        if not cursor:
            break
    return total


async def snapshot_all_active_to_legacy(archive_index: str) -> dict[str, int]:
    """Snapshot every active index in the registry. Returns counts per
    source index. Used as the Phase-0 safety backup before re-ingest runs."""
    db: Session = SessionLocal()
    try:
        active = (
            db.query(IndexRegistry)
            .filter(IndexRegistry.is_active == True)  # noqa: E712
            .all()
        )
        results: dict[str, int] = {}
        for entry in active:
            try:
                count = await snapshot_to_legacy(
                    entry.index_name, entry.project_id, archive_index
                )
                results[entry.index_name] = count
                _log.info(
                    "snapshotted %s: %d chunks", entry.index_name, count
                )
            except Exception as exc:
                _log.error("snapshot failed for %s: %s", entry.index_name, exc)
                results[entry.index_name] = -1
        return results
    finally:
        db.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("job_id")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO)
    asyncio.run(run_ingest_job(args.job_id))


if __name__ == "__main__":
    main()
