"""Phase-0 re-ingest pipeline.

Pulls chunks from a source Pinecone index, reconstructs documents when
metadata supports it, semantic re-chunks with Cohere, enriches metadata
via LLM, and upserts into a target index/namespace.

Idempotent: ``ingest_jobs.processed_chunks`` advances per upsert; rerunning
resumes from offset (NFR-REL-6).

Usage:
    python -m app.scripts.reingest <ingest_job_id>
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import uuid
from datetime import datetime
from pathlib import Path
from string import Template
from typing import Any

from sqlalchemy.orm import Session

from app.db.database import SessionLocal
from app.models.index_registry import IndexRegistry
from app.models.ingest_job import IngestJob
from app.services.chunking_service import semantic_chunk_text
from app.services.embedding_service import generate_embeddings_cohere_batch
from app.services.llm_service import call_openai_json
from app.services.pinecone_service import get_factory

_log = logging.getLogger(__name__)

_BATCH_SIZE = 96  # Cohere embed batch limit
_FAILURE_THRESHOLD = 0.05  # halt at 5% chunk failure rate
_METADATA_MODEL = "gpt-4.1-mini"
_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "metadata_enrich.txt"


async def fetch_source_chunks(
    index_name: str, project_id: str, batch_size: int = 100,
) -> list[dict[str, Any]]:
    """Paginate the source index, return all chunks with metadata.

    Uses ``list_paginated`` to iterate vector IDs, then ``fetch`` in batches
    to pull text + metadata. Vector values are NOT returned — they'll be
    re-generated by Cohere v3 in the ingest pipeline.
    """
    factory = get_factory()
    client = factory.get_client(project_id)
    index = client.Index(index_name)

    all_ids: list[str] = []
    cursor: str | None = None
    while True:
        page = index.list_paginated(limit=batch_size, pagination_token=cursor)
        all_ids.extend(v.id for v in page.vectors)
        cursor = page.pagination.next if page.pagination else None
        if not cursor:
            break

    chunks: list[dict[str, Any]] = []
    for i in range(0, len(all_ids), 100):
        batch = all_ids[i:i + 100]
        fetched = index.fetch(ids=batch)
        for vid, vec in fetched.vectors.items():
            md = vec.metadata or {}
            chunks.append({"id": vid, "text": md.get("text", ""), "metadata": md})
    return chunks


def reconstruct_documents(chunks: list[dict[str, Any]]) -> dict[str, str]:
    """Group chunks back into source documents by ``source_id`` where
    available. Chunks without ``source_id`` are kept as standalone documents
    keyed by ``_orphan_<i>``."""
    grouped: dict[str, list[tuple[int, str]]] = {}
    orphans: list[str] = []
    for c in chunks:
        md = c.get("metadata") or {}
        sid = md.get("source_id")
        if sid:
            pos = md.get("chunk_position", 0)
            grouped.setdefault(sid, []).append((pos, c["text"]))
        else:
            orphans.append(c["text"])

    docs: dict[str, str] = {}
    for sid, items in grouped.items():
        items.sort(key=lambda t: t[0])
        docs[sid] = "\n\n".join(text for _, text in items)
    for i, text in enumerate(orphans):
        docs[f"_orphan_{i}"] = text
    return docs


async def enrich_metadata(chunk_text: str) -> dict[str, Any]:
    """LLM pass to extract topic_tags, source_type, public_safe."""
    prompt = Template(_PROMPT_PATH.read_text()).safe_substitute(
        chunk_text=chunk_text[:2000]
    )
    return await call_openai_json(
        model=_METADATA_MODEL, system="", user=prompt, temperature=0
    )
